version: '3'

services:
  database:
    imgae: 'postgres:latest'

    ports: 
      - '5432:5432'
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: carrinhodecompras